name: "Tests the App"
env:
  DB_PROVIDER: ${{ vars.DB_PROVIDER }}
  DB_URL: ${{ secrets.DB_URL }}
on:
  push:
    branches:
      - main
jobs:
  run_test:
    name: "Run tests"
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases

    steps:
    - uses: actions/checkout@v3
    - name: Install modules
      run: npm ci
    - name: Check code formatting
      run: npm run lint
    - name: Migrate the database
      run: npm run db:migrate
    - name: Seed the data
      run: npm run db:seed
    - name: Run unit tests
      run: npm run test
    - name: Run e2e tests
      run: npm run test:e2e
    - name: Build
      run: npm run build
